#
# Macro file for the initialization phase of "exampleN06.cc"
# when running in interactive mode
#
# Sets some default verbose
#
/control/verbose 2
/run/verbose 2
#
# create empty scene
#
/vis/scene/create
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#
#/vis/open DAWNFILE
/vis/open OGLIQt
#
#/vis/viewer/zoom 1.5
/vis/viewer/flush
#
# for drawing the tracks
# Draw trajectories at end of event, showing trajectory points as
# markers of size 2 pixels
/vis/scene/add/trajectories
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 1
/vis/modeling/trajectories/drawByParticleID-0/set gamma blue
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton green
/vis/modeling/trajectories/drawByParticleID-0/setRGBA mu- 1 0 1 1

# (if too many tracks cause core dump => storeTrajectory 0)
#
/vis/scene/endOfEventAction accumulate
#
# Refresh ready for run
/vis/viewer/refresh
##
/vis/geometry/set/colour Cathode 10 red
/vis/geometry/set/colour WLS_log 10 green
/geometry/test/run
# Now ready for /run/beamOn.
#/tracking/verbose 1
/gun/particle mu-
/gun/position 0 -15 0
/gun/direction 0 -1 0
/gun/momentumAmp 4 GeV
#/run/beamOn 1
